server:
  port: 8888
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  
spring:
  cloud:
    gateway:
      routes:
      - id: dashboard-service
        uri: lb://DASHBOARD-SERVICE
        predicates:
        - Path=/dashboard/**
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**  
